# Generated by Django 5.0.6 on 2025-09-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-period', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_code',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
