# Generated by Django 5.0.6 on 2025-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['block', 'number'],
                'unique_together': {('block', 'number')},
            },
        ),
    ]
