# Generated by Django 5.0.6 on 2025-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['house_number']},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='house_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='block',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='number',
        ),
    ]
