# Generated by Django 5.0.6 on 2025-09-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(choices=[('FACE', 'Face')], default='FACE', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detections/%Y/%m/%d/')),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
