# Generated by Django 5.0.6 on 2025-09-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resident_type', models.CharField(choices=[('OWNER', 'Owner'), ('TENANT', 'Tenant')], max_length=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='units.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unit__block', 'unit__number', 'user__email'],
                'unique_together': {('user', 'unit', 'start_date')},
            },
        ),
    ]
