# Generated by Django 5.0.6 on 2025-09-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['unit__house_number', 'user__email']},
        ),
    ]
