# Generated by Django 5.0.6 on 2025-09-27 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0002_alter_resident_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('id_doc', models.CharField(blank=True, max_length=40)),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('gate', models.CharField(default='Principal', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('allowed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_registered', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residents.resident')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='visitors_vi_created_9081d7_idx'), models.Index(fields=['resident'], name='visitors_vi_residen_e4cd34_idx')],
            },
        ),
    ]
