# Generated by Django 5.0.6 on 2025-09-28 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_resident_options'),
        ('visitors', '0002_visitorentry_delete_visitorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=120)),
                ('visitor_id', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('PEDESTRIAN', 'Peatón'), ('VEHICLE', 'Vehículo')], default='PEDESTRIAN', max_length=12)),
                ('status', models.CharField(choices=[('IN', 'Ingresó'), ('OUT', 'Salida registrada')], default='IN', max_length=6)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('guard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_visits', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to='residents.resident')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
        migrations.DeleteModel(
            name='VisitorEntry',
        ),
    ]
