# Generated by Django 5.0.6 on 2025-09-28 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('residents', '0002_alter_resident_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonarea',
            name='description',
        ),
        migrations.AddField(
            model_name='commonarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commonarea',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.commonarea')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='residents.resident')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('area', 'date', 'start_time', 'end_time'), name='uniq_area_slot'),
        ),
    ]
