# Generated by Django 5.0.6 on 2025-09-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_commonarea_description_commonarea_is_active_and_more'),
        ('residents', '0002_alter_resident_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonarea',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commonarea',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonarea',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.commonarea')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='residents.resident')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'unique_together': {('area', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
