# Generated by Django 5.0.6 on 2025-09-21 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0002_alter_resident_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('photo_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En Proceso'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='residents.resident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
